name: login_ui_flutter
description: Login UI - Flutter
# @CodeWithFlexz on Instagram
# AmirBayat0 on Github
# Programming with Flexz on Youtub

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  line_icons: ^2.0.1
  animate_do: ^2.1.0
  ionicons: ^0.2.2
  font_awesome_flutter: ^10.0.0
  google_mlkit_text_recognition: ^0.11.0
  path_provider: ^2.1.2
  shimmer: ^2.0.0
  provider: ^6.0.5
  uuid: ^3.0.6
  image_picker: ^0.8.7+5
  #image_picker: ^1.0.4




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
